### ISSUE TITLE
sassc: invalid option -- 'a'

### ISSUE THREAD

**Issue by YerayAlonso** [willscreel/Communitheme-MATE#1]
I'm getting this error when running the script:

> patching file gtk-communitheme/Communitheme/gtk-3.0/_colors.scss
> patching file gtk-communitheme/Communitheme/gtk-2.0/gtkrc
> patching file gtk-communitheme/Communitheme/index.theme
> patching file gtk-communitheme/Communitheme/meson.build
> patching file gtk-communitheme/Communitheme/gtk-3.0/_ubuntu-colors.scss
> The Meson build system
> Version: 0.42.1
> Source dir: /home/norike/Descargas/Communitheme-MATE-master/gtk-communitheme
> Build dir: /home/norike/Descargas/Communitheme-MATE-master/gtk-communitheme/builddir
> Build type: native build
> Project name: gtk-communitheme
> Build machine cpu family: x86_64
> Build machine cpu: x86_64
> Program sassc found: YES (/usr/local/bin/sassc)
> Build targets in project: 2
> ninja: Entering directory `builddir'
> [1/3] Generating generate_gtk with a custom command.
> FAILED: Communitheme/gtk-3.0/gtk.css 
> /usr/local/bin/sassc -a ../Communitheme/gtk-3.0/gtk.scss Communitheme/gtk-3.0/gtk.css
> /usr/local/bin/sassc: invalid option -- 'a'
> See '/usr/local/bin/sassc -h'
> [2/3] Generating generate_gtk-dark with a custom command.
> FAILED: Communitheme/gtk-3.0/gtk-dark.css 
> /usr/local/bin/sassc -a ../Communitheme/gtk-3.0/gtk-dark.scss Communitheme/gtk-3.0/gtk-dark.css
> /usr/local/bin/sassc: invalid option -- 'a'
> See '/usr/local/bin/sassc -h'
> ninja: build stopped: subcommand failed.
> ln: fallo al crear el enlace simbólico '/home/norike/.themes/Communitheme-MATE': El archivo ya existe

Am I overlooking anything?

**Comment by willscreel** [comment]
It's probably because of your version of sassc is different.  I was building this on Ubuntu 17.10.

**Comment by YerayAlonso** [comment]
How did you install sassc?  
I'm getting the error above in a virtual machine running Ubuntu Mate 17.10.1 from live.
